### ISSUE TITLE
Investigate other mdl + react projects

### ISSUE THREAD

**Issue by niksurff** [nikvm/material-design-react#5]
Stop and contribute elsewhere if someone does a better job than we do.
- https://github.com/neftaly/react-mdl
- https://github.com/ironhee/react-mtl
- https://github.com/pksunkara/react-mdl
- https://github.com/eferte/react-mdl
- https://github.com/react-mdl/react-mdl
- https://github.com/nicolascava/react-mdl
- https://github.com/Fandora/mdl-react
- ...

**Comment by Semigradsky** [comment]
https://github.com/neftaly/react-mdl looks good

**Comment by niksurff** [comment]
Thanks @Semigradsky. Seems like under the hood it's not to different than what I am doing. Also his take on component interfaces is not what I am planning. That said, I will keep an eye on it.

**Comment by adamalbrecht** [comment]
Looks like https://github.com/Fandora/mdl-react is really coming along.

**Comment by niksurff** [comment]
Thanks for the suggestion @adamalbrecht! Definitely more complete. But again the interface is to much for my taste (adding extra style props for example). Also I feel I am to far along now to give this project up as suggested in my first comment.

**Comment by detj** [comment]
How does this look to you?
https://github.com/tleunen/react-mdl

There is a mention of a bug present in MDL 1.0.4 which clashes with React and the fix for this is going to land in MDL 2.0

I have also come across this when using `mdl-js-layout` and related classes. Do you have any thoughts on how this should be handled?

I also found [this](http://www.heapoverflow.me/question-using-material-design-lite-with-react-31998227) and I quote

> MDL massively changes your markup and that is exactly what React doesn't like.

Would like to hear your views on it.

**Comment by niksurff** [comment]
Thanks for stopping by, @detj.

[tleunen/react-mdl](https://github.com/tleunen/react-mdl) seems like the best option for using MDL with React right now, as it is most complete and updated regularly. But I haven't tried to integrate it into a project so far.

As the linked to question and answers mention I too solved the `mdl-layout` problem by wrapping  `<div class="mdl-layout mdl-js-layout" />` in another `div`. It at least keeps errors from occurring.
I haven't impinged on any other errors so far.

Personally, I can just hope MDL 2.0 comes out before the React app I use it with goes to production.
Also in my opinion v1.x is definitely usable with React if you don't mind using some hacks to get around it's imperfections.
