### ISSUE TITLE
Get some folks on board

### ISSUE THREAD

**Issue by niksurff** [nikvm/material-design-react#6]

**Comment by detj** [comment]
Looking forward to your work on this.

**Comment by detj** [comment]
Have you used http://material-ui.com/? What are your thoughts on it?

**Comment by niksurff** [comment]
HI @detj, thanks I am pushing a bigger update in the next couple days.

I am working on a React application using Material Design. That's the main reason I started this project and am willing to keep working on it.
We used [http://material-ui.com/](material ui) in our prototype, that was  before [Material Design Lite](https://github.com/google/material-design-lite) was announced.
Main reasons for the switch are
- material ui now uses inline styles which seemed promising but proved unsuitable for our project
- material design lite is as official as it gets and providing a light React wrapper shouldn't be to complicated

Also see [this discussion](https://github.com/callemall/material-ui/issues/1049) of implementing mdl in material ui.

**Comment by detj** [comment]
Thanks for the comments. Yeah, it would be great to closely follow [Material Design Light](http://www.getmdl.io) with [React](http://facebook.github.io/react/), though from the other thread its clear its quite a bit of a work. How are planning to maintain this project as [Material Design Light](http://getmdl.io) matures?

**Comment by niksurff** [comment]
Material ui and other material design implementations implement their own styles and functionality (ripple effect, drawer opening/closing etc.). I offload all this to mdl. The only thing I am doing right now is translating React components and their props to html elements and mdl's BEM classes which is a lot less work and error prone. So best case scenario: mdl gets updated and you just use their new .css and .js files. Also I may add some more sugar/ React features in the future.

Of course this is all just thick air right now as only the Button component is implemented but more components coming this week...

**Comment by niksurff** [comment]
Hello Stargazers @detj, @bvleur, @kexplo, @coniel, @cristiangraz, @engleek, @kyrre, @JohnSmithX, @mattsahr, @fabiozaffani, @seyhbold, @oliviercardoen, @pandaiolo, @adamalbrecht, @gaurav-

I hereby invite you to a contribution. :octocat:

Let's get the :soccer: rolling. To get started have a look at [the guide](https://github.com/nikvm/material-design-react/blob/master/CONTRIBUTING.md). Thanks to everyone!

**Comment by engleek** [comment]
Hi there!

_My two cents:_

I've read through the guide and the source, and I think each component could be implemented as a full React component. Each could import the appropriate SCSS files and then implement the logic in the relevant JS files.

This might seem like a lot of work, but the source in each JS file is relatively simple. Each one just manages state, logic and events for transitioning between classnames and adds some elements. It might even be simpler as a React component.

Check out [the source for buttons](https://github.com/google/material-design-lite/blob/master/src/button/button.js). It's really familiar.

Second thing is the name of the module/repo. With so many Material Design projects floating around, IMHO it would be helpful to rename the module/repo to something like "react-mdl" or "react-material-design-lite" so people know it's based on the official implementation.

**Comment by niksurff** [comment]
Thanks for your input @engleek, further discussion [here](https://github.com/nikvm/material-design-react/issues/12).
